import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the <a href="https://archivve.visualizevalue.com/">Visual Artchive!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://ozolinsjanis.com/" className={styles.card}>
            <h2>Janis Ozolins &rarr;</h2>
            <p>Check out the website of Janis.</p>
          </a>

          <a href="https://archivve.visualizevalue.com/" className={styles.card}>
            <h2>Visualise Value &rarr;</h2>
            <p>Check out all the visuals created by Visualise Value - curated by Satya </p>
          </a>

          <a
            href="https://vyshnav.xyz/visuals"
            className={styles.card}
          >
            <h2>Vyshnav &rarr;</h2>
            <p>Check out all the visuals created by Vyshnav </p>
          </a>

          <a
            href="https://mounika.studio/"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
            Check out all the visuals created by Mounika
            </p>
          </a>
        </div>
      </main>

              {
  "extends": "next",
  "rules": {
    "react/no-unescaped-entities": "off",
    "@next/next/no-page-custom-font": "off"
  }
}
              
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Kaleidoscope and {' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
